# Generated by Django 3.0.5 on 2020-04-28 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0004_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Review',
            new_name='review',
        ),
    ]
